# Generated by Django 5.1.6 on 2025-03-07 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualizacionOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actualizaciones', to='reparaciones.ordenreparacion')),
            ],
        ),
    ]
